appURL1=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
appURL2=https://tutorialsninja.com/demo/
Username=Ninjapotter
email=Ninjapotter@gmail.com
Password=Ninja
reviewerName=Kavi
inputreviewcontent=The Apple Monitor is good to use, Must buy!! and worth the price. Please dont think just go for it.
ratingValue=5